# Generated by Django 4.2.5 on 2023-11-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0002_alter_registered_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered',
            name='budget',
            field=models.CharField(choices=[('1', '5000-10000'), ('2', '10000-20000'), ('3', '20000-30000'), ('4', 'Above 30000')], default='1', max_length=2),
        ),
    ]
