# Generated by Django 4.2.5 on 2023-11-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0003_alter_registered_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
